# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FindPeminjam.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FindPeminjam(object):
    def setupUi(self, FindPeminjam):
        FindPeminjam.setObjectName("FindPeminjam")
        FindPeminjam.resize(275, 245)
        self.tblData = QtWidgets.QTableWidget(FindPeminjam)
        self.tblData.setGeometry(QtCore.QRect(10, 10, 256, 192))
        self.tblData.setObjectName("tblData")
        self.tblData.setColumnCount(2)
        self.tblData.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblData.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblData.setHorizontalHeaderItem(1, item)
        self.btnSelect = QtWidgets.QPushButton(FindPeminjam)
        self.btnSelect.setGeometry(QtCore.QRect(190, 210, 75, 23))
        self.btnSelect.setObjectName("btnSelect")

        self.retranslateUi(FindPeminjam)
        QtCore.QMetaObject.connectSlotsByName(FindPeminjam)

    def retranslateUi(self, FindPeminjam):
        _translate = QtCore.QCoreApplication.translate
        FindPeminjam.setWindowTitle(_translate("FindPeminjam", "Cari Peminjam"))
        item = self.tblData.horizontalHeaderItem(0)
        item.setText(_translate("FindPeminjam", "Kode"))
        item = self.tblData.horizontalHeaderItem(1)
        item.setText(_translate("FindPeminjam", "Nama"))
        self.btnSelect.setText(_translate("FindPeminjam", "Select"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FindPeminjam = QtWidgets.QDialog()
    ui = Ui_FindPeminjam()
    ui.setupUi(FindPeminjam)
    FindPeminjam.show()
    sys.exit(app.exec_())
