# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FindBuku.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FindBuku(object):
    def setupUi(self, FindBuku):
        FindBuku.setObjectName("FindBuku")
        FindBuku.resize(275, 245)
        self.btnSelect = QtWidgets.QPushButton(FindBuku)
        self.btnSelect.setGeometry(QtCore.QRect(190, 210, 75, 23))
        self.btnSelect.setDefault(True)
        self.btnSelect.setObjectName("btnSelect")
        self.tblData = QtWidgets.QTableWidget(FindBuku)
        self.tblData.setGeometry(QtCore.QRect(10, 10, 256, 192))
        self.tblData.setAlternatingRowColors(True)
        self.tblData.setObjectName("tblData")
        self.tblData.setColumnCount(2)
        self.tblData.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblData.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblData.setHorizontalHeaderItem(1, item)

        self.retranslateUi(FindBuku)
        QtCore.QMetaObject.connectSlotsByName(FindBuku)
        FindBuku.setTabOrder(self.tblData, self.btnSelect)

    def retranslateUi(self, FindBuku):
        _translate = QtCore.QCoreApplication.translate
        FindBuku.setWindowTitle(_translate("FindBuku", "Cari Buku"))
        self.btnSelect.setText(_translate("FindBuku", "Select"))
        item = self.tblData.horizontalHeaderItem(0)
        item.setText(_translate("FindBuku", "Kode"))
        item = self.tblData.horizontalHeaderItem(1)
        item.setText(_translate("FindBuku", "Judul"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FindBuku = QtWidgets.QDialog()
    ui = Ui_FindBuku()
    ui.setupUi(FindBuku)
    FindBuku.show()
    sys.exit(app.exec_())
